server:
  port: 8080

spring:
  application:
    name: runus

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect  # Hibernate Dialect 설정 추가
        show_sql: true
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  # 파일 크기 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

  config:
    import: application-db.yml, application-security.yml

  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    com.fourback: DEBUG

